site_name: vyper.rocks
theme:
  name: material
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
 - 'index.md'
 - 'concepts.md'
 - 'evm.md'